spring:
  application:
    name: reffics-groupware    
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.30:5432/refficstest
    username: refficstest
    password: fpvlrtm1!
    